
-- euler #1 

-- If we list all the natural numbers below 10 that are multiples of 3
-- or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
-- 
-- Find the sum of all the multiples of 3 or 5 below 1000.

-- 233168
euler1 = sum [x | x <- take 1000 [0..], x `mod` 3 == 0 || x `mod` 5 == 0]


-- euler #2

-- Each new term in the Fibonacci sequence is generated by adding the
-- previous two terms. By starting with 1 and 2, the first 10 terms
-- will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...  Find the sum of
-- all the even-valued terms in the sequence which do not exceed four
-- million.

fibs = 0 : 1 : zipWith (+) fibs (tail fibs)

euler2 = ... 